Repository openshift/sriov-dp-admission-controller, pull requests merged in 2019-07, with the labels that each got.

#10 Fix resource and add third party certificate
  deployments/server.yaml
  deployments/service.yaml
  deployments/webhook.yaml
  docs/installation.md
  pkg/webhook/webhook.go
  scripts/webhook-deployment.sh
  scripts/webhook-patch-ca-bundle.sh
Labels: lgtm, size/L

#11 Downward api
  pkg/webhook/webhook.go
  scripts/build-image.sh
Labels: lgtm, size/M

#12 restart http server upon cert file update (#14)
  cmd/webhook/main.go
  pkg/webhook/tlsutils.go
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.github/ISSUE_TEMPLATE.md
  vendor/github.com/fsnotify/fsnotify/.github/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/example_test.go
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/fsnotify_test.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller_test.go
  vendor/github.com/fsnotify/fsnotify/inotify_test.go
  vendor/github.com/fsnotify/fsnotify/integration_darwin_test.go
  vendor/github.com/fsnotify/fsnotify/integration_test.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: lgtm, size/XXL

#13 build.sh: remove no_openssl
  scripts/build.sh
Labels: lgtm, size/XS
