Repository openshift/sriov-dp-admission-controller, pull requests merged in 2023-11, with the labels that each got.

#69 OCPBUGS-22313: Enable fips compliance
  scripts/build.sh
Labels: lgtm, approved, needs-ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#67 Bump image and base image to RHEL 9
  .ci-operator.yaml
  Dockerfile.rhel7
Labels: lgtm, approved, ok-to-test

#70 OCPBUGS-22365: Enable fips compliance
  scripts/build.sh
Labels: lgtm, approved, needs-ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#73 OCPBUGS-22156: Fix HTTP/2 disablement
  cmd/webhook/main.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#74 OCPBUGS-21047: Fix HTTP/2 disablement
  cmd/webhook/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#65 OCPBUGS-20993: disable HTTP/2 by default
  cmd/webhook/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#71 OCPBUGS-22370: Enable fips compliance
  scripts/build.sh
Labels: lgtm, approved, needs-ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
